[package]
name = "s4-solana-native-program"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "1.5.1"
borsh-derive = "1.5.1"
solana-program = "1.18.17"

[lib]
name = "s4_solana_native_program"
crate-type = ["cdylib", "lib"]
